Description: Fix run_tests.py for Django 1.9 compat
Author: Thomas Goirand <zigo@debian.org>
Bug-Debian: https://bugs.debian.org/806365
Forwarded: no
Last-Update: 2016-01-11

Index: python-jingo/run_tests.py
===================================================================
--- python-jingo.orig/run_tests.py
+++ python-jingo/run_tests.py
@@ -10,9 +10,11 @@ os.environ['DJANGO_SETTINGS_MODULE'] = '
 os.environ['PYTHONPATH'] = os.pathsep.join([ROOT,
                                             os.path.join(ROOT, 'examples')])
 
+import django
+if hasattr(django, 'setup'):
+    django.setup()
+
+from django.contrib.contenttypes.models import ContentType
+
 if __name__ == '__main__':
-    if hasattr(django, 'setup'):
-        # Django's app registry was added in 1.7. We need to call `setup` to
-        # initiate it.
-        django.setup()
     nose.main()
